### ISSUE TITLE
File is missing ?

### ISSUE THREAD

**Issue by KiraAmora61** [ReactiioN1337/license-system#3]
Hii

File is missing?

http://prntscr.com/oql9ob

**Comment by lurumdare** [comment]
Recursive git help you

**Comment by KiraAmora61** [comment]
where can i get help ?

**Comment by lurumdare** [comment]
install SmartGit and clone repo

**Comment by ReactiioN1337** [comment]
As @lurumdare said, clone the repository recursive using `git clone --recursive https://github.com/ReactiioN1337/license-system.git`
