### ISSUE TITLE
License generator

### ISSUE THREAD

**Issue by lurumdare** [ReactiioN1337/license-system#4]
Supported?

**Comment by ReactiioN1337** [comment]
What do you mean and how is this an issue?

**Comment by lurumdare** [comment]
About subscriber and HWID.

**Comment by lurumdare** [comment]
How to add `hwid_hash` and api token for valid user.

**Comment by ReactiioN1337** [comment]
You don't need to set `hwid_hash` yourself. 

https://github.com/ReactiioN1337/license-system/blob/master/backend/src/backend.js#L52

**Comment by ReactiioN1337** [comment]
Adding a new user is also supported, I suggest you to read the readme and/or the code.

https://github.com/ReactiioN1337/license-system/tree/master/backend#adduser
